FROM centos:7

RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum -y install https://rpms.remirepo.net/enterprise/remi-release-7.rpm

RUN yum update -y

RUN yum -y install yum-utils
RUN yum-config-manager --disable 'remi-php*'
RUN yum-config-manager --enable remi-php80
RUN yum -y install php php-{cli,fpm,mysqlnd,zip,devel,gd,mbstring,curl,xml,pear,bcmath,json,common}
RUN yum install -y httpd php8w php8w-opcache

RUN yum install -y ImageMagick.x86_64 vim git cronie.x86_64
RUN yum groupinstall -y 'Development Tools'

VOLUME ["/var/www/html/", "/etc/httpd/", "/var/log/"]

#
# Install composer
#
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
php composer-setup.php --install-dir=/usr/local/bin  --filename=composer && \
php -r "unlink('composer-setup.php');"

#
# Install node js
#
RUN cd /tmp && curl https://nodejs.org/dist/v14.18.3/node-v14.18.3-linux-x64.tar.xz -O
RUN tar -xf /tmp/node-v14.18.3-linux-x64.tar.xz -C /usr/local/
ENV PATH "${PATH}:/usr/local/node-v14.18.3-linux-x64/bin/"
RUN npm install yarn -g

COPY files/httpd.conf /etc/httpd/conf/httpd.conf

CMD /usr/sbin/httpd -k start -DFOREGROUND




